name: Build and push images

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_call:
  workflow_dispatch:

jobs:
  build-n-push:
    runs-on: ubuntu-latest
    environment: production
    steps:
    - uses: actions/checkout@v4
    - name: Docker Login
      uses: docker/login-action@v2.0.0
      with:
        username: ${{ secrets.DOCKER_REGISTRY_USER }}
        password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
    - name: Build the Docker image
      run: docker build --build-arg NUXT_PUBLIC_API_BASE_URL=${{ vars.API_BASE_URL }} -t minhhikari/giaolypoc-fe:latest .
    - name: Push the "latest" image
      run: docker push "minhhikari/giaolypoc-fe:latest"

  trigger-deployment:
    needs: build-n-push
    uses: ./.github/workflows/deploy-on-prod.yml
    secrets: inherit
  